import 'babel-polyfill';
import React from 'react';
import ReactDOM from "react-dom";
import App from './app';

let countries = [{
    "id": 1,
    "country": "Afghanistan"
}, {
    "id": 2,
    "country": "Germany"
}, {
    "id": 3,
    "country": "Albania"
}, {
    "id": 4,
    "country": "China"
}, {
    "id": 5,
    "country": "Indonesia"
}, {
    "id": 6,
    "country": "Czech Republic"
}, {
    "id": 7,
    "country": "Syria"
}, {
    "id": 8,
    "country": "Iceland"
}, {
    "id": 9,
    "country": "Guinea"
}, {
    "id": 10,
    "country": "Angola"
}, {
    "id": 11,
    "country": "Denmark"
}, {
    "id": 12,
    "country": "Sri Lanka"
}, {
    "id": 13,
    "country": "Finland"
}, {
    "id": 14,
    "country": "Russia"
}, {
    "id": 15,
    "country": "Philippines"
}, {
    "id": 16,
    "country": "India"
}, {
    "id": 17,
    "country": "Eritrea"
}, {
    "id": 18,
    "country": "Latvia"
}, {
    "id": 19,
    "country": "Sao Tome and Principe"
}, {
    "id": 20,
    "country": "Poland"
}, {
    "id": 21,
    "country": "Argentina"
}, {
    "id": 22,
    "country": "Argentina"
}, {
    "id": 23,
    "country": "Portugal"
}, {
    "id": 24,
    "country": "Portugal"
}, {
    "id": 25,
    "country": "Armenia"
}, {
    "id": 26,
    "country": "Russia"
}, {
    "id": 27,
    "country": "Brazil"
}, {
    "id": 28,
    "country": "Australia"
}, {
    "id": 29,
    "country": "Poland"
}, {
    "id": 30,
    "country": "Sweden"
}, {
    "id": 31,
    "country": "Gabon"
}, {
    "id": 32,
    "country": "Kosovo"
}, {
    "id": 33,
    "country": "El Salvador"
}, {
    "id": 34,
    "country": "Iran"
}, {
    "id": 35,
    "country": "Portugal"
}, {
    "id": 36,
    "country": "Iraq"
}, {
    "id": 37,
    "country": "Peru"
}, {
    "id": 38,
    "country": "Egypt"
}, {
    "id": 39,
    "country": "Russia"
}, {
    "id": 40,
    "country": "Thailand"
}, {
    "id": 41,
    "country": "Bahrain"
}, {
    "id": 42,
    "country": "Ireland"
}, {
    "id": 43,
    "country": "Philippines"
}, {
    "id": 44,
    "country": "Bangladesh"
}, {
    "id": 45,
    "country": "Armenia"
}, {
    "id": 46,
    "country": "Israel"
}, {
    "id": 47,
    "country": "Jamaica"
}, {
    "id": 48,
    "country": "Barbados"
}, {
    "id": 49,
    "country": "Ecuador"
}, {
    "id": 50,
    "country": "Japan"
}, {
    "id": 51,
    "country": "Yemen"
}, {
    "id": 52,
    "country": "Slovenia"
}, {
    "id": 53,
    "country": "Belgium"
}, {
    "id": 54,
    "country": "Benin"
}, {
    "id": 55,
    "country": "Philippines"
}, {
    "id": 56,
    "country": "Bhutan"
}, {
    "id": 57,
    "country": "Bolivia"
}, {
    "id": 58,
    "country": "Pakistan"
}, {
    "id": 59,
    "country": "Djibouti"
}, {
    "id": 60,
    "country": "Botswana"
}, {
    "id": 61,
    "country": "Greece"
}, {
    "id": 62,
    "country": "Cambodia"
}, {
    "id": 63,
    "country": "Palestinian Territory"
}, {
    "id": 64,
    "country": "Philippines"
}, {
    "id": 65,
    "country": "Albania"
}, {
    "id": 66,
    "country": "Georgia"
}, {
    "id": 67,
    "country": "Ghana"
}, {
    "id": 68,
    "country": "Cameroon"
}, {
    "id": 69,
    "country": "Greece"
}, {
    "id": 70,
    "country": "Chad"
}, {
    "id": 71,
    "country": "Guatemala"
}, {
    "id": 72,
    "country": "Jordan"
}, {
    "id": 73,
    "country": "Chile"
}, {
    "id": 74,
    "country": "South Korea"
}, {
    "id": 75,
    "country": "Colombia"
}, {
    "id": 76,
    "country": "Philippines"
}, {
    "id": 77,
    "country": "Comoros"
}, {
    "id": 78,
    "country": "Dominica"
}, {
    "id": 79,
    "country": "Nigeria"
}, {
    "id": 80,
    "country": "Costa Rica"
}, {
    "id": 81,
    "country": "France"
}, {
    "id": 82,
    "country": "Kazakhstan"
}, {
    "id": 83,
    "country": "Poland"
}, {
    "id": 84,
    "country": "Portugal"
}, {
    "id": 85,
    "country": "Kosovo"
}, {
    "id": 86,
    "country": "Croatia"
}, {
    "id": 87,
    "country": "Serbia"
}, {
    "id": 88,
    "country": "Kuwait"
}, {
    "id": 89,
    "country": "Cuba"
}, {
    "id": 90,
    "country": "Kenya"
}, {
    "id": 91,
    "country": "Cyprus"
}, {
    "id": 92,
    "country": "Russia"
}, {
    "id": 93,
    "country": "Pakistan"
}, {
    "id": 94,
    "country": "Portugal"
}, {
    "id": 95,
    "country": "Burma"
}, {
    "id": 96,
    "country": "Brunei "
}, {
    "id": 97,
    "country": "South Korea"
}, {
    "id": 98,
    "country": "Finland"
}, {
    "id": 99,
    "country": "Poland"
}, {
    "id": 100,
    "country": "United States"
}]


ReactDOM.render(<App countries={countries} />,
    document.getElementById('root')
);
