import 'babel-polyfill';
import React from 'react';
import ReactDOM from "react-dom";
import App from './app';

let contacts = [{
    "id": 1,
    "name": "Debra",
    "last": "Ray"
}, {
    "id": 2,
    "name": "Robin",
    "last": "Burns"
}, {
    "id": 3,
    "name": "Lori",
    "last": "Andrews"
}, {
    "id": 4,
    "name": "Denise",
    "last": "Anderson"
}, {
    "id": 5,
    "name": "Heather",
    "last": "Williamson"
}, {
    "id": 6,
    "name": "Steve",
    "last": "Allen"
}, {
    "id": 7,
    "name": "Richard",
    "last": "Bennett"
}, {
    "id": 8,
    "name": "Roger",
    "last": "Lawrence"
}, {
    "id": 9,
    "name": "Debra",
    "last": "Watson"
}, {
    "id": 10,
    "name": "Theresa",
    "last": "Hart"
}, {
    "id": 11,
    "name": "Linda",
    "last": "Bell"
}, {
    "id": 12,
    "name": "Stephanie",
    "last": "Hall"
}, {
    "id": 13,
    "name": "Marie",
    "last": "Perkins"
}, {
    "id": 14,
    "name": "Roger",
    "last": "Burke"
}, {
    "id": 15,
    "name": "Earl",
    "last": "Tucker"
}, {
    "id": 16,
    "name": "Irene",
    "last": "Burton"
}, {
    "id": 17,
    "name": "Deborah",
    "last": "Anderson"
}, {
    "id": 18,
    "name": "Martin",
    "last": "Boyd"
}, {
    "id": 19,
    "name": "Christopher",
    "last": "Williamson"
}, {
    "id": 20,
    "name": "Gary",
    "last": "Stewart"
}, {
    "id": 21,
    "name": "Debra",
    "last": "Marshall"
}, {
    "id": 22,
    "name": "Carol",
    "last": "Tucker"
}, {
    "id": 23,
    "name": "Susan",
    "last": "Dean"
}, {
    "id": 24,
    "name": "Louis",
    "last": "Roberts"
}, {
    "id": 25,
    "name": "John",
    "last": "Hicks"
}, {
    "id": 26,
    "name": "Louise",
    "last": "Baker"
}, {
    "id": 27,
    "name": "Shirley",
    "last": "Bailey"
}, {
    "id": 28,
    "name": "Joshua",
    "last": "Nelson"
}, {
    "id": 29,
    "name": "Kathleen",
    "last": "Morris"
}, {
    "id": 30,
    "name": "Earl",
    "last": "Martin"
}, {
    "id": 31,
    "name": "Evelyn",
    "last": "Rodriguez"
}, {
    "id": 32,
    "name": "Louis",
    "last": "Brown"
}, {
    "id": 33,
    "name": "Dennis",
    "last": "Hill"
}, {
    "id": 34,
    "name": "Jason",
    "last": "Olson"
}, {
    "id": 35,
    "name": "Willie",
    "last": "Hunt"
}, {
    "id": 36,
    "name": "Emily",
    "last": "Banks"
}, {
    "id": 37,
    "name": "Jeremy",
    "last": "Torres"
}, {
    "id": 38,
    "name": "Linda",
    "last": "Wells"
}, {
    "id": 39,
    "name": "Henry",
    "last": "Rice"
}, {
    "id": 40,
    "name": "Jeremy",
    "last": "Murphy"
}, {
    "id": 41,
    "name": "Shawn",
    "last": "Fox"
}, {
    "id": 42,
    "name": "Craig",
    "last": "Bradley"
}, {
    "id": 43,
    "name": "Adam",
    "last": "Brooks"
}, {
    "id": 44,
    "name": "Martin",
    "last": "Alexander"
}, {
    "id": 45,
    "name": "Louis",
    "last": "Bell"
}, {
    "id": 46,
    "name": "Ronald",
    "last": "Frazier"
}, {
    "id": 47,
    "name": "Harry",
    "last": "Holmes"
}, {
    "id": 48,
    "name": "Norma",
    "last": "Brooks"
}, {
    "id": 49,
    "name": "Anne",
    "last": "King"
}, {
    "id": 50,
    "name": "Kimberly",
    "last": "Chapman"
}, {
    "id": 51,
    "name": "Rebecca",
    "last": "Hill"
}, {
    "id": 52,
    "name": "Jeremy",
    "last": "Young"
}, {
    "id": 53,
    "name": "Sandra",
    "last": "Chavez"
}, {
    "id": 54,
    "name": "Carol",
    "last": "Garcia"
}, {
    "id": 55,
    "name": "Brenda",
    "last": "Turner"
}, {
    "id": 56,
    "name": "Kimberly",
    "last": "Scott"
}, {
    "id": 57,
    "name": "Thomas",
    "last": "Watson"
}, {
    "id": 58,
    "name": "George",
    "last": "Torres"
}, {
    "id": 59,
    "name": "Virginia",
    "last": "Robinson"
}, {
    "id": 60,
    "name": "Emily",
    "last": "Parker"
}, {
    "id": 61,
    "name": "Betty",
    "last": "Gardner"
}, {
    "id": 62,
    "name": "Philip",
    "last": "West"
}, {
    "id": 63,
    "name": "Jimmy",
    "last": "Hanson"
}, {
    "id": 64,
    "name": "Martha",
    "last": "Fox"
}, {
    "id": 65,
    "name": "Earl",
    "last": "Stephens"
}, {
    "id": 66,
    "name": "Richard",
    "last": "Greene"
}, {
    "id": 67,
    "name": "Richard",
    "last": "Ward"
}, {
    "id": 68,
    "name": "Donald",
    "last": "Mason"
}, {
    "id": 69,
    "name": "Joan",
    "last": "Harrison"
}, {
    "id": 70,
    "name": "Martha",
    "last": "Powell"
}, {
    "id": 71,
    "name": "Amy",
    "last": "Moore"
}, {
    "id": 72,
    "name": "Benjamin",
    "last": "Little"
}, {
    "id": 73,
    "name": "Philip",
    "last": "Bishop"
}, {
    "id": 74,
    "name": "Antonio",
    "last": "Ellis"
}, {
    "id": 75,
    "name": "Jesse",
    "last": "Adams"
}, {
    "id": 76,
    "name": "Evelyn",
    "last": "Murray"
}, {
    "id": 77,
    "name": "Annie",
    "last": "Gray"
}, {
    "id": 78,
    "name": "Howard",
    "last": "Fox"
}, {
    "id": 79,
    "name": "Ashley",
    "last": "Pierce"
}, {
    "id": 80,
    "name": "Craig",
    "last": "Russell"
}, {
    "id": 81,
    "name": "Harold",
    "last": "Weaver"
}, {
    "id": 82,
    "name": "Wayne",
    "last": "Shaw"
}, {
    "id": 83,
    "name": "Frank",
    "last": "Henderson"
}, {
    "id": 84,
    "name": "Craig",
    "last": "Lee"
}, {
    "id": 85,
    "name": "Diane",
    "last": "Bishop"
}, {
    "id": 86,
    "name": "Michael",
    "last": "Garza"
}, {
    "id": 87,
    "name": "Sharon",
    "last": "Sullivan"
}, {
    "id": 88,
    "name": "William",
    "last": "Roberts"
}, {
    "id": 89,
    "name": "Ann",
    "last": "Watson"
}, {
    "id": 90,
    "name": "Justin",
    "last": "Coleman"
}, {
    "id": 91,
    "name": "Christine",
    "last": "Young"
}, {
    "id": 92,
    "name": "Maria",
    "last": "Bailey"
}, {
    "id": 93,
    "name": "Brian",
    "last": "Franklin"
}, {
    "id": 94,
    "name": "Jacqueline",
    "last": "Garrett"
}, {
    "id": 95,
    "name": "Pamela",
    "last": "Moore"
}, {
    "id": 96,
    "name": "Annie",
    "last": "Lee"
}, {
    "id": 97,
    "name": "Jacqueline",
    "last": "Sullivan"
}, {
    "id": 98,
    "name": "Christine",
    "last": "Griffin"
}, {
    "id": 99,
    "name": "George",
    "last": "Harris"
}, {
    "id": 100,
    "name": "Frank",
    "last": "Phillips"
}]

ReactDOM.render(<App contacts={contacts} />,
    document.getElementById('root')
);
